Fix test dirs chmods errors.
Stragely, when run on digitalocean jessie x64 droplet (as root), the
following error were produced before this fix:

======================================================================
ERROR: test_add_name_vhost (letsencrypt.client.plugins.apache.tests.configurator_test.TwoVhost80Test)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/root/lets-encrypt-preview/letsencrypt/client/plugins/apache/tests/configurator_test.py", line 35, in setUp
self.ssl_options)
File "/root/lets-encrypt-preview/letsencrypt/client/plugins/apache/tests/util.py", line 76, in get_apache_configurator
version)
File "/root/lets-encrypt-preview/letsencrypt/client/plugins/apache/configurator.py", line 96, in __init__
self.verify_setup()
File "/root/lets-encrypt-preview/letsencrypt/client/plugins/apache/configurator.py", line 938, in verify_setup
self.config.config_dir, constants.CONFIG_DIRS_MODE, uid)
File "/root/lets-encrypt-preview/letsencrypt/client/le_util.py", line 37, in make_or_verify_dir
"permissions or owner" % directory)
LetsEncryptClientError: /tmp/tmp1wYWIMconfig exists, but does not have the proper permissions or owner